"""Add claude_models table

Revision ID: 002
Revises: 001
Create Date: 2025-07-06 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "002"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claude_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("input_price", sa.Float(), nullable=False),
        sa.Column("output_price", sa.Float(), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=True),
        sa.Column("supports_vision", sa.Boolean(), nullable=True),
        sa.Column("supports_tool_use", sa.Boolean(), nullable=True),
        sa.Column("supports_computer_use", sa.Boolean(), nullable=True),
        sa.Column("supports_extended_thinking", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("is_deprecated", sa.Boolean(), nullable=True),
        sa.Column("release_date", sa.String(), nullable=True),
        sa.Column("model_family", sa.String(), nullable=True),
        sa.Column("model_tier", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claude_models_id"), "claude_models", ["id"], unique=False)
    op.create_index(
        op.f("ix_claude_models_model_id"), "claude_models", ["model_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_claude_models_model_id"), table_name="claude_models")
    op.drop_index(op.f("ix_claude_models_id"), table_name="claude_models")
    op.drop_table("claude_models")
    # ### end Alembic commands ###
